<!-- Primary Page Layout
================================================== -->

<header id="header" class="site-header" role="banner">
	<div id="header-inner" class="container sixteen columns over">
	<hgroup class="one-third column alpha">
		<h1 id="site-title" class="site-title">
			<a href="home" id="logo"><img src="<c:url value='/includes/images/rmap_logo_small.png'/>" alt="RMap logo" height="80" width="160" /></a>
		</h1>
	</hgroup>
	<nav id="main-nav" class="two thirds column omega">
		<ul id="main-nav-menu" class="nav-menu">
			<li id="menu-item-1">
				<a href="<c:url value='/home'/>">Home</a>
			</li>
			<li id="menu-item-2">
				<a href="<c:url value='/search'/>">Search</a>
			</li>
			<li id="menu-item-3">
				<a href="<c:url value='/contact'/>">Contact</a>
			</li>
			<li id="menu-item-4">
				<a href="<c:url value='/user/signin'/>">Sign in</a>
				<ul class="dropdown-menu">
					<li><a href="<c:url value='/user/keys'/>">Manage API keys</a></li>
					<li><a href="<c:url value='/user/reports'/>">View API activity</a></li>
					<li><a href="<c:url value='/user/settings'/>">Settings</a></li>
					<li><a href="<c:url value='/logout'/>">Logout</a></li>
				</ul>
			</li>
		</ul>
	</nav>
</div>
</header>

<div class="container">



