	<!-- Primary Page Layout
	================================================== -->

	<header id="header" class="site-header" role="banner">
    <div id="header-inner" class="container sixteen columns over">
    <hgroup class="one-third column alpha">
    <h1 id="site-title" class="site-title">
    <a href="home" id="logo"><img src="includes/images/rmap_logo_small.png" alt="RMap logo" height="80" width="160" /></a>
    </h1>
    </hgroup>
    <nav id="main-nav" class="two thirds column omega">
    <ul id="main-nav-menu" class="nav-menu">
    <li id="menu-item-1">
    <a href="home">Home</a>
    </li>
    <li id="menu-item-2">
    <a href="search">Search</a>
    </li>
    <li id="menu-item-3">
    <a href="contact">Contact</a>
    </li>
    <li id="menu-item-4">
    <a href="login">Login</a>
    </li>
    </ul>
    </nav>
    </div>
    </header>

	<div class="container">

		
		
		