
   	 </article>
    </div>

<footer>

<div class="footer-inner container">

	<div class="social footer-columns one-third column">
		<h2><i class="icon-bullhorn icon-large"></i> Related Links</h2>
		<p>You can learn more about the RMap Project through these connections:</p>
		<ul>
			<li><a href="http://rmap-project.info"><i class="icon-twitter-sign icon-large"></i> RMap Project website</a></li>
			<li><a href="http://www.twitter.com/RMapProject"><i class="icon-twitter-sign icon-large"></i> Twitter</a></li>
			<li><a href="https://www.youtube.com/channel/UCZ7SDybbfgM_XH7zfIWc89Q"><i class="icon-twitter-sign icon-large"></i> YouTube</a></li>
		</ul>
	</div>

	<div class="footer-columns one-third column">
		<h2><i class="icon-book icon-large"></i> Funding</h2>
		<p>The project is funded by the Alfred P. Sloan Foundation and undertaken by the Data Conservancy, Portico, and IEEE.</p>
	</div>

	<div class="footer-columns one-third column">
		<h2><i class="icon-user icon-large"></i> About Us</h2>
		<p>The goal of the RMap Project is to create a prototype service that can capture the maps of relationships amongst the components of a modern scholarly publication, and preserve those maps over the long term.</p>
	</div>

</div>

<div id="footer-base">
	<div class="container">
		<div class="eight columns">
			<a href="http://www.opendesigns.org/design/icebrrrg/">Icebrrg Website Template</a> &copy; 2012
		</div>

		<div class="eight columns far-edge">
			Design by <a href="http://www.opendesigns.org">OD</a>
		</div>
	</div>
	</div>

</footer>

<!-- End Document
================================================== -->

</body>
</html>